### ISSUE TITLE
Setup wizard failing on system config setup

### ISSUE THREAD

**Issue by cmelgarejo** [polterguy/magic.deploy#1]
I believe I configured everything as should be, easy as it gets, but once you get to the setup screen the backend fails at this step, is this a known issue?

I believe this is the offending part:

`magic.node.extensions.HyperlambdaException: Dynamic slot [magic.db..databases] does not exist in scope` 

magic.dbmaybe I'm missing a config? setting up the database type? where would that config might be?

I hope this can get resolved maybe I can lend a hand too if you want to, I found your product by chance and I gotta say it's really awesome! I'm eager to give it a spin!

A (almost) full stacktrace with more info:

```bash
frontend  | 172.18.0.2 - - [25/Jan/2024:21:53:13 +0000] "GET /ngsw.json?ngsw-cache-bust=0.5661112920016947 HTTP/1.1" 200 9006 "https://magic.mysiteredacted.com/ngsw-worker.js" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" "108.108.108.108"
backend   | info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
backend   |       Request starting HTTP/1.1 OPTIONS http://magic-api.mysiteredacted.com/magic/system/config/setup - -
backend   | info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
backend   |       CORS policy execution successful.
backend   | info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
backend   |       Request finished HTTP/1.1 OPTIONS http://magic-api.mysiteredacted.com/magic/system/config/setup - - - 204 - - 0.3762ms
backend   | info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
backend   |       Request starting HTTP/1.1 POST http://magic-api.mysiteredacted.com/magic/system/config/setup application/json 93
backend   | info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
backend   |       CORS policy execution successful.
backend   | info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
backend   |       Executing endpoint 'magic.endpoint.controller.EndpointController.Execute (magic.endpoint.controller)'
backend   | info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
backend   |       Route matched with {action = "Execute", controller = "Endpoint"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Execute(System.String) on controller magic.endpoint.controller.EndpointController (magic.endpoint.controller).
backend   | info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
backend   |       Executed action magic.endpoint.controller.EndpointController.Execute (magic.endpoint.controller) in 2146.5355ms
backend   | info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
backend   |       Executed endpoint 'magic.endpoint.controller.EndpointController.Execute (magic.endpoint.controller)'
backend   | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
backend   |       An unhandled exception has occurred while executing the request.
backend   |       magic.node.extensions.HyperlambdaException: Dynamic slot [magic.db..databases] does not exist in scope
backend   |          at magic.lambda.slots.SignalSlot.GetLambda(ISignaler signaler, Node input, Boolean throws)
backend   |          at magic.lambda.slots.SignalSlot.<>c__DisplayClass3_0.<<SignalAsync>b__0>d.MoveNext()
backend   |       --- End of stack trace from previous location ---
backend   |          at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
backend   |          at magic.lambda.slots.SignalSlot.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.eval.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes)
backend   |          at magic.lambda.eval.Eval.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.io.file.ExecuteFile.<>c__DisplayClass4_0.<<SignalAsync>b__0>d.MoveNext()
backend   |       --- End of stack trace from previous location ---
backend   |          at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
backend   |          at magic.lambda.io.file.ExecuteFile.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.eval.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes)
backend   |          at magic.lambda.eval.Eval.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.branching.If.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.eval.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes)
backend   |          at magic.lambda.eval.Eval.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.exceptions.Try.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.lambda.exceptions.Try.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.lambda.eval.Eval.ExecuteAsync(ISignaler signaler, IEnumerable`1 nodes)
backend   |          at magic.lambda.eval.Eval.SignalAsync(ISignaler signaler, Node input)
backend   |          at magic.signals.services.Signaler.SignalAsync(String name, Node input, Action functor)
backend   |          at magic.endpoint.services.HttpApiExecutorAsync.<>c__DisplayClass6_0.<<ExecuteAsync>b__2>d.MoveNext()
backend   |       --- End of stack trace from previous location ---
backend   |          at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
backend   |          at magic.endpoint.services.HttpApiExecutorAsync.<>c__DisplayClass6_0.<<ExecuteAsync>b__1>d.MoveNext()
backend   |       --- End of stack trace from previous location ---
backend   |          at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
backend   |          at magic.endpoint.services.HttpApiExecutorAsync.<>c__DisplayClass6_0.<<ExecuteAsync>b__0>d.MoveNext()
backend   |       --- End of stack trace from previous location ---
backend   |          at magic.signals.services.Signaler.ScopeAsync(String name, Object value, Func`1 functor)
backend   |          at magic.endpoint.services.HttpApiExecutorAsync.ExecuteAsync(Node lambda, MagicRequest request)
backend   |          at magic.endpoint.services.HttpApiExecutorAsync.ExecuteAsync(MagicRequest request)
backend   |          at magic.endpoint.controller.EndpointController.HandleRequest(String verb, String url)
backend   |          at magic.endpoint.controller.EndpointController.Execute(String url)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
backend   |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
backend   |          at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
backend   |          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
backend   |          at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
backend   | info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
backend   |       Request finished HTTP/1.1 POST http://magic-api.mysiteredacted.com/magic/system/config/setup application/json 93 - 500 - application/json 2219.5305ms
```

**Comment by cmelgarejo** [comment]
Actually I went down the `docker/volumes/magicdeploy_magic_config_files/_data/appsettings.json` and the db section I see it like:

```json
   "databases": {
      "default": null,
      "": {
        "generic": null
      }
```

might that be it, @polterguy ?

**Comment by cmelgarejo** [comment]
I think I locked down to the config getting set as `null` after the setup step, I just modified again to point to the default sqlite db, but the setup step is truncated, and the db is empty no first user, just FYI.
